In [11]:
import pandas as pd
df2016 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2016.csv')
df2017 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2017.csv')
df2018 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2018.csv')
df2019 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2019.csv')
df2020 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2020.csv')
df2021 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀투수_2021.csv')

In [12]:
total = pd.concat([df2016, df2017, df2018, df2019, df2020, df2021])
total

              G_ID   GDAY_DS T_ID  ... P_WHIP_RT  P2_WHIP_RT CB_WHIP_RT
0    20160401HHLG0  20160401   LG  ...  0.642857         0.0   2.400000
1    20160401HHLG0  20160401   HH  ...  1.500000         0.0   0.750000
2    20160401HTNC0  20160401   NC  ...  1.333333         0.0   2.142857
3    20160401HTNC0  20160401   HT  ...  0.500000         0.0   1.875000
4    20160401KTSK0  20160401   SK  ...  1.000000         0.0   2.250000
..             ...       ...  ...  ...       ...         ...        ...
763  20210711HHSK0  20210711   HH  ...  1.363636         0.0   1.500000
764  20210711KTHT0  20210711   HT  ...  0.600000         0.0   0.250000
765  20210711KTHT0  20210711   KT  ...  1.500000         0.0   0.333333
766  20210711LTSS0  20210711   LT  ...  2.142857         0.0   1.666667
767  20210711LTSS0  20210711   SS  ...  0.375000         0.0   0.900000

[7968 rows x 35 columns]

In [18]:
df = total[['G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'WLS']]
df

              G_ID   GDAY_DS T_ID VS_T_ID  HEADER_NO WLS
0    20160401HHLG0  20160401   LG      HH          0   W
1    20160401HHLG0  20160401   HH      LG          0   L
2    20160401HTNC0  20160401   NC      HT          0   W
3    20160401HTNC0  20160401   HT      NC          0   L
4    20160401KTSK0  20160401   SK      KT          0   L
..             ...       ...  ...     ...        ...  ..
763  20210711HHSK0  20210711   HH      SK          0   L
764  20210711KTHT0  20210711   HT      KT          0   W
765  20210711KTHT0  20210711   KT      HT          0   L
766  20210711LTSS0  20210711   LT      SS          0   L
767  20210711LTSS0  20210711   SS      LT          0   W

[7968 rows x 6 columns]

In [20]:
df = df.drop(['G_ID'], axis=1)
df

      GDAY_DS T_ID VS_T_ID  HEADER_NO WLS
0    20160401   LG      HH          0   W
1    20160401   HH      LG          0   L
2    20160401   NC      HT          0   W
3    20160401   HT      NC          0   L
4    20160401   SK      KT          0   L
..        ...  ...     ...        ...  ..
763  20210711   HH      SK          0   L
764  20210711   HT      KT          0   W
765  20210711   KT      HT          0   L
766  20210711   LT      SS          0   L
767  20210711   SS      LT          0   W

[7968 rows x 5 columns]

In [23]:
df['WLS'].value_counts()

L    3937
W    3937
D      94
Name: WLS, dtype: int64